### ISSUE TITLE
Access lab-b

### ISSUE THREAD

**Issue by ngv83** [a-mcf/DnnLab#1]
Hi,

The credentials do not work for lab b just a.
Any ideas?

Thanks!

**Comment by a-mcf** [comment]
Interesting. I spun one up last week, and was just able to log into it. I'll take a look this evening and see if I can duplicate the issue. I'm not (yet anyway, it's planned) doing anything to set the password at all, so assuming it installs correctly, it SHOULD be using the default credentials.

**Comment by ngv83** [comment]
I managed to add another website to the installation, now I have two environments.
Thanks for looking into that.

**Comment by a-mcf** [comment]
I spun up an instance of this today on a different machine, and was able to login to "lab-b" with the host/dnnhost credentials. I did have a problem with "Features on Demand" in Windows Server 2012 R2 not downloading .net framework the first time through, but when I re-ran `vagrant up` it seemed to go.

Every once in a while, the DNN installer will fail on one instance or the other. In these cases, you can remove the website's directory and database, but it's often just as easy to just destroy the install and vagrant up again.

I'm inclined to think that you had something quirky happen during the DNN install, and am going to close this out. That said, please let me know if you continue to have issues and maybe I can grab some logs or something from you. 

![image](https://cloud.githubusercontent.com/assets/7788354/22133542/cc1fb626-de8e-11e6-98c0-aad42e9db50f.png)

**Comment by ngv83** [comment]
I was thinking the installation did not happen correctly. I will give a try in another machi and will let you know if I have any issue.

Thanks,

Napo.
